// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using isg_crm.Data;

#nullable disable

namespace isg_crm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250810094501_SeedManager")]
    partial class SeedManager
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("isg_crm.Models.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38cc51b3-41fc-4d4c-a791-6cc2c98e921a"),
                            CreatedAt = new DateTime(2025, 8, 10, 9, 45, 1, 613, DateTimeKind.Utc).AddTicks(8960),
                            Email = "admin@isg.com",
                            Name = "Sistem Yöneticisi",
                            Password = "$2a$11$PaJJon0daMjcZesLVEodUuLEVsqswecGZ/8laCjBFwvfaHQdpaX2G",
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 8, 10, 9, 45, 1, 613, DateTimeKind.Utc).AddTicks(8960),
                            Uuid = new Guid("1d737574-09fb-4d55-8f1b-3ac7c68fe0dd")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
