// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using isg_crm.Data;

#nullable disable

namespace isg_crm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("isg_crm.Models.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43d0563d-96de-42a4-a79f-1bebaa967c40"),
                            CreatedAt = new DateTime(2025, 8, 10, 14, 10, 7, 627, DateTimeKind.Utc).AddTicks(4710),
                            Email = "admin@isg.com",
                            Name = "Sistem Admini",
                            Password = "$2a$11$nTEFBE2nLvTa43vwJ6jnZ.OPzcmSR7Df/WgJd83GpaCW3qKDlWatC",
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 8, 10, 14, 10, 7, 627, DateTimeKind.Utc).AddTicks(4710),
                            Uuid = new Guid("6e776394-1af5-4c4d-b373-3f7d8f2bc34d")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
